import os
import psycopg
from psycopg.rows import dict_row
from pwdlib import PasswordHash
from dotenv import load_dotenv

load_dotenv()

password_hash = PasswordHash.recommended()

conexao = psycopg.connect(
    dbname=os.getenv("DB_NAME"),
    user=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD"),
    host=os.getenv("DB_HOST"),
    port=os.getenv("DB_PORT")
)

cursor = conexao.cursor(row_factory=dict_row)

def criar_tabela():
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS produtos (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome TEXT NOT NULL,
            preco REAL NOT NULL,
            estoque INTEGER NOT NULL
        )
    """)
    conexao.commit()

def listar_produtos():
    cursor.execute("SELECT * FROM produtos ORDER BY id ASC")
    resultados = cursor.fetchall()
    return [dict(produto) for produto in resultados]

def buscar_produtos_nome(nome):
    cursor.execute("SELECT * FROM produtos WHERE nome = %s", (nome,))
    resultados = cursor.fetchall()
    if resultados:
        return [dict(produto) for produto in resultados]

def buscar_produto_id(id):
    cursor.execute("SELECT * FROM produtos WHERE id = %s", (id,))
    resultado = cursor.fetchone()
    if resultado:
        return dict(resultado)

def adicionar_produto(nome, preco, estoque):
    cursor.execute("""
        INSERT INTO produtos (nome, preco, estoque)
        VALUES (%s, %s, %s)
        RETURNING id
    """, (nome, preco, estoque))

    novo_id = cursor.fetchone()["id"]
    conexao.commit()
    return novo_id

def atualizar_produto_db(id, nome, preco, estoque):
    cursor.execute("""
        UPDATE produtos
        SET nome = %s, preco = %s, estoque = %s
        WHERE id = %s
    """, (nome, preco, estoque, id))
    conexao.commit()

def excluir_produto_db(id):
    cursor.execute("""
        DELETE FROM produtos
        WHERE id = %s
    """, (id,))
    conexao.commit()

def buscar_produtos_estoque(quantidade):
    cursor.execute("""
        SELECT * FROM produtos
        WHERE estoque <= %s
    """, (quantidade,))
    return cursor.fetchall()

def criar_tabela_usuarios():
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS usuarios (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT UNIQUE NOT NULL,
            senha TEXT NOT NULL
        )
    """)
    conexao.commit()

def adicionar_usuario(username, senha):
    hash_senha = password_hash.hash(senha)

    cursor.execute("""
        INSERT INTO usuarios (username, senha)
        VALUES (%s, %s)
    """, (username, hash_senha))
    conexao.commit()

def buscar_usuario_username(username):
    cursor.execute("""
        SELECT * FROM usuarios WHERE username = %s
    """, (username,))
    resultado = cursor.fetchone()
    if resultado:
        return dict(resultado)
    return None

def verificar_senha(senha, hash_senha):
    return password_hash.verify(senha, hash_senha)
